//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMIWrappers.Raw {
    
    
    public class Msvm_ComputerSystem : WMIWrapper {
        
        public Msvm_ComputerSystem(System.Management.ManagementObject instance) : 
                base(instance) {
        }
        
        public virtual ushort[] AvailableRequestedStates {
            get {
                return ((ushort[])(Instance["AvailableRequestedStates"]));
            }
            set {
                Instance["AvailableRequestedStates"] = value;
            }
        }
        
        public virtual string Caption {
            get {
                return ((string)(Instance["Caption"]));
            }
            set {
                Instance["Caption"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> CommunicationStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["CommunicationStatus"]));
            }
            set {
                Instance["CommunicationStatus"] = value;
            }
        }
        
        public virtual string CreationClassName {
            get {
                return ((string)(Instance["CreationClassName"]));
            }
            set {
                Instance["CreationClassName"] = value;
            }
        }
        
        public virtual ushort[] Dedicated {
            get {
                return ((ushort[])(Instance["Dedicated"]));
            }
            set {
                Instance["Dedicated"] = value;
            }
        }
        
        public virtual string Description {
            get {
                return ((string)(Instance["Description"]));
            }
            set {
                Instance["Description"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> DetailedStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["DetailedStatus"]));
            }
            set {
                Instance["DetailedStatus"] = value;
            }
        }
        
        public virtual string ElementName {
            get {
                return ((string)(Instance["ElementName"]));
            }
            set {
                Instance["ElementName"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> EnabledDefault {
            get {
                return ((System.Nullable<ushort>)(Instance["EnabledDefault"]));
            }
            set {
                Instance["EnabledDefault"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> EnabledState {
            get {
                return ((System.Nullable<ushort>)(Instance["EnabledState"]));
            }
            set {
                Instance["EnabledState"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> EnhancedSessionModeState {
            get {
                return ((System.Nullable<ushort>)(Instance["EnhancedSessionModeState"]));
            }
            set {
                Instance["EnhancedSessionModeState"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> FailedOverReplicationType {
            get {
                return ((System.Nullable<ushort>)(Instance["FailedOverReplicationType"]));
            }
            set {
                Instance["FailedOverReplicationType"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> HealthState {
            get {
                return ((System.Nullable<ushort>)(Instance["HealthState"]));
            }
            set {
                Instance["HealthState"] = value;
            }
        }
        
        public virtual string[] IdentifyingDescriptions {
            get {
                return ((string[])(Instance["IdentifyingDescriptions"]));
            }
            set {
                Instance["IdentifyingDescriptions"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> InstallDate {
            get {
                return ParseDate(Instance["InstallDate"]);
            }
            set {
                Instance["InstallDate"] = value;
            }
        }
        
        public virtual string InstanceID {
            get {
                return ((string)(Instance["InstanceID"]));
            }
            set {
                Instance["InstanceID"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> LastApplicationConsistentReplicationTime {
            get {
                return ParseDate(Instance["LastApplicationConsistentReplicationTime"]);
            }
            set {
                Instance["LastApplicationConsistentReplicationTime"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> LastReplicationTime {
            get {
                return ParseDate(Instance["LastReplicationTime"]);
            }
            set {
                Instance["LastReplicationTime"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> LastReplicationType {
            get {
                return ((System.Nullable<ushort>)(Instance["LastReplicationType"]));
            }
            set {
                Instance["LastReplicationType"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> LastSuccessfulBackupTime {
            get {
                return ParseDate(Instance["LastSuccessfulBackupTime"]);
            }
            set {
                Instance["LastSuccessfulBackupTime"] = value;
            }
        }
        
        public virtual string Name {
            get {
                return ((string)(Instance["Name"]));
            }
            set {
                Instance["Name"] = value;
            }
        }
        
        public virtual string NameFormat {
            get {
                return ((string)(Instance["NameFormat"]));
            }
            set {
                Instance["NameFormat"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> NumberOfNumaNodes {
            get {
                return ((System.Nullable<ushort>)(Instance["NumberOfNumaNodes"]));
            }
            set {
                Instance["NumberOfNumaNodes"] = value;
            }
        }
        
        public virtual System.Nullable<ulong> OnTimeInMilliseconds {
            get {
                return ((System.Nullable<ulong>)(Instance["OnTimeInMilliseconds"]));
            }
            set {
                Instance["OnTimeInMilliseconds"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> OperatingStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["OperatingStatus"]));
            }
            set {
                Instance["OperatingStatus"] = value;
            }
        }
        
        public virtual ushort[] OperationalStatus {
            get {
                return ((ushort[])(Instance["OperationalStatus"]));
            }
            set {
                Instance["OperationalStatus"] = value;
            }
        }
        
        public virtual string[] OtherDedicatedDescriptions {
            get {
                return ((string[])(Instance["OtherDedicatedDescriptions"]));
            }
            set {
                Instance["OtherDedicatedDescriptions"] = value;
            }
        }
        
        public virtual string OtherEnabledState {
            get {
                return ((string)(Instance["OtherEnabledState"]));
            }
            set {
                Instance["OtherEnabledState"] = value;
            }
        }
        
        public virtual string[] OtherIdentifyingInfo {
            get {
                return ((string[])(Instance["OtherIdentifyingInfo"]));
            }
            set {
                Instance["OtherIdentifyingInfo"] = value;
            }
        }
        
        public virtual ushort[] PowerManagementCapabilities {
            get {
                return ((ushort[])(Instance["PowerManagementCapabilities"]));
            }
            set {
                Instance["PowerManagementCapabilities"] = value;
            }
        }
        
        public virtual string PrimaryOwnerContact {
            get {
                return ((string)(Instance["PrimaryOwnerContact"]));
            }
            set {
                Instance["PrimaryOwnerContact"] = value;
            }
        }
        
        public virtual string PrimaryOwnerName {
            get {
                return ((string)(Instance["PrimaryOwnerName"]));
            }
            set {
                Instance["PrimaryOwnerName"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> PrimaryStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["PrimaryStatus"]));
            }
            set {
                Instance["PrimaryStatus"] = value;
            }
        }
        
        public virtual System.Nullable<uint> ProcessID {
            get {
                return ((System.Nullable<uint>)(Instance["ProcessID"]));
            }
            set {
                Instance["ProcessID"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> ReplicationHealth {
            get {
                return ((System.Nullable<ushort>)(Instance["ReplicationHealth"]));
            }
            set {
                Instance["ReplicationHealth"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> ReplicationMode {
            get {
                return ((System.Nullable<ushort>)(Instance["ReplicationMode"]));
            }
            set {
                Instance["ReplicationMode"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> ReplicationState {
            get {
                return ((System.Nullable<ushort>)(Instance["ReplicationState"]));
            }
            set {
                Instance["ReplicationState"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> RequestedState {
            get {
                return ((System.Nullable<ushort>)(Instance["RequestedState"]));
            }
            set {
                Instance["RequestedState"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> ResetCapability {
            get {
                return ((System.Nullable<ushort>)(Instance["ResetCapability"]));
            }
            set {
                Instance["ResetCapability"] = value;
            }
        }
        
        public virtual string[] Roles {
            get {
                return ((string[])(Instance["Roles"]));
            }
            set {
                Instance["Roles"] = value;
            }
        }
        
        public virtual string Status {
            get {
                return ((string)(Instance["Status"]));
            }
            set {
                Instance["Status"] = value;
            }
        }
        
        public virtual string[] StatusDescriptions {
            get {
                return ((string[])(Instance["StatusDescriptions"]));
            }
            set {
                Instance["StatusDescriptions"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeOfLastConfigurationChange {
            get {
                return ParseDate(Instance["TimeOfLastConfigurationChange"]);
            }
            set {
                Instance["TimeOfLastConfigurationChange"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeOfLastStateChange {
            get {
                return ParseDate(Instance["TimeOfLastStateChange"]);
            }
            set {
                Instance["TimeOfLastStateChange"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> TransitioningToState {
            get {
                return ((System.Nullable<ushort>)(Instance["TransitioningToState"]));
            }
            set {
                Instance["TransitioningToState"] = value;
            }
        }
    }
}
