//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMIWrappers.Raw {
    
    
    public class Msvm_ConcreteJob : WMIWrapper {
        
        public Msvm_ConcreteJob(System.Management.ManagementObject instance) : 
                base(instance) {
        }
        
        public virtual System.Nullable<bool> Cancellable {
            get {
                return ((System.Nullable<bool>)(Instance["Cancellable"]));
            }
            set {
                Instance["Cancellable"] = value;
            }
        }
        
        public virtual string Caption {
            get {
                return ((string)(Instance["Caption"]));
            }
            set {
                Instance["Caption"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> CommunicationStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["CommunicationStatus"]));
            }
            set {
                Instance["CommunicationStatus"] = value;
            }
        }
        
        public virtual System.Nullable<bool> DeleteOnCompletion {
            get {
                return ((System.Nullable<bool>)(Instance["DeleteOnCompletion"]));
            }
            set {
                Instance["DeleteOnCompletion"] = value;
            }
        }
        
        public virtual string Description {
            get {
                return ((string)(Instance["Description"]));
            }
            set {
                Instance["Description"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> DetailedStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["DetailedStatus"]));
            }
            set {
                Instance["DetailedStatus"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> ElapsedTime {
            get {
                return ParseDate(Instance["ElapsedTime"]);
            }
            set {
                Instance["ElapsedTime"] = value;
            }
        }
        
        public virtual string ElementName {
            get {
                return ((string)(Instance["ElementName"]));
            }
            set {
                Instance["ElementName"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> ErrorCode {
            get {
                return ((System.Nullable<ushort>)(Instance["ErrorCode"]));
            }
            set {
                Instance["ErrorCode"] = value;
            }
        }
        
        public virtual string ErrorDescription {
            get {
                return ((string)(Instance["ErrorDescription"]));
            }
            set {
                Instance["ErrorDescription"] = value;
            }
        }
        
        public virtual string ErrorSummaryDescription {
            get {
                return ((string)(Instance["ErrorSummaryDescription"]));
            }
            set {
                Instance["ErrorSummaryDescription"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> HealthState {
            get {
                return ((System.Nullable<ushort>)(Instance["HealthState"]));
            }
            set {
                Instance["HealthState"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> InstallDate {
            get {
                return ParseDate(Instance["InstallDate"]);
            }
            set {
                Instance["InstallDate"] = value;
            }
        }
        
        public virtual string InstanceID {
            get {
                return ((string)(Instance["InstanceID"]));
            }
            set {
                Instance["InstanceID"] = value;
            }
        }
        
        public virtual System.Nullable<uint> JobRunTimes {
            get {
                return ((System.Nullable<uint>)(Instance["JobRunTimes"]));
            }
            set {
                Instance["JobRunTimes"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> JobState {
            get {
                return ((System.Nullable<ushort>)(Instance["JobState"]));
            }
            set {
                Instance["JobState"] = value;
            }
        }
        
        public virtual string JobStatus {
            get {
                return ((string)(Instance["JobStatus"]));
            }
            set {
                Instance["JobStatus"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> JobType {
            get {
                return ((System.Nullable<ushort>)(Instance["JobType"]));
            }
            set {
                Instance["JobType"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> LocalOrUtcTime {
            get {
                return ((System.Nullable<ushort>)(Instance["LocalOrUtcTime"]));
            }
            set {
                Instance["LocalOrUtcTime"] = value;
            }
        }
        
        public virtual string Name {
            get {
                return ((string)(Instance["Name"]));
            }
            set {
                Instance["Name"] = value;
            }
        }
        
        public virtual string Notify {
            get {
                return ((string)(Instance["Notify"]));
            }
            set {
                Instance["Notify"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> OperatingStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["OperatingStatus"]));
            }
            set {
                Instance["OperatingStatus"] = value;
            }
        }
        
        public virtual ushort[] OperationalStatus {
            get {
                return ((ushort[])(Instance["OperationalStatus"]));
            }
            set {
                Instance["OperationalStatus"] = value;
            }
        }
        
        public virtual string OtherRecoveryAction {
            get {
                return ((string)(Instance["OtherRecoveryAction"]));
            }
            set {
                Instance["OtherRecoveryAction"] = value;
            }
        }
        
        public virtual string Owner {
            get {
                return ((string)(Instance["Owner"]));
            }
            set {
                Instance["Owner"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> PercentComplete {
            get {
                return ((System.Nullable<ushort>)(Instance["PercentComplete"]));
            }
            set {
                Instance["PercentComplete"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> PrimaryStatus {
            get {
                return ((System.Nullable<ushort>)(Instance["PrimaryStatus"]));
            }
            set {
                Instance["PrimaryStatus"] = value;
            }
        }
        
        public virtual System.Nullable<uint> Priority {
            get {
                return ((System.Nullable<uint>)(Instance["Priority"]));
            }
            set {
                Instance["Priority"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> RecoveryAction {
            get {
                return ((System.Nullable<ushort>)(Instance["RecoveryAction"]));
            }
            set {
                Instance["RecoveryAction"] = value;
            }
        }
        
        public virtual System.Nullable<byte> RunDay {
            get {
                return ((System.Nullable<byte>)(Instance["RunDay"]));
            }
            set {
                Instance["RunDay"] = value;
            }
        }
        
        public virtual System.Nullable<byte> RunDayOfWeek {
            get {
                return ((System.Nullable<byte>)(Instance["RunDayOfWeek"]));
            }
            set {
                Instance["RunDayOfWeek"] = value;
            }
        }
        
        public virtual System.Nullable<sbyte> RunMonth {
            get {
                return ((System.Nullable<sbyte>)(Instance["RunMonth"]));
            }
            set {
                Instance["RunMonth"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> RunStartInterval {
            get {
                return ParseDate(Instance["RunStartInterval"]);
            }
            set {
                Instance["RunStartInterval"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> ScheduledStartTime {
            get {
                return ParseDate(Instance["ScheduledStartTime"]);
            }
            set {
                Instance["ScheduledStartTime"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> StartTime {
            get {
                return ParseDate(Instance["StartTime"]);
            }
            set {
                Instance["StartTime"] = value;
            }
        }
        
        public virtual string Status {
            get {
                return ((string)(Instance["Status"]));
            }
            set {
                Instance["Status"] = value;
            }
        }
        
        public virtual string[] StatusDescriptions {
            get {
                return ((string[])(Instance["StatusDescriptions"]));
            }
            set {
                Instance["StatusDescriptions"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeBeforeRemoval {
            get {
                return ParseDate(Instance["TimeBeforeRemoval"]);
            }
            set {
                Instance["TimeBeforeRemoval"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeOfLastStateChange {
            get {
                return ParseDate(Instance["TimeOfLastStateChange"]);
            }
            set {
                Instance["TimeOfLastStateChange"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeSubmitted {
            get {
                return ParseDate(Instance["TimeSubmitted"]);
            }
            set {
                Instance["TimeSubmitted"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> UntilTime {
            get {
                return ParseDate(Instance["UntilTime"]);
            }
            set {
                Instance["UntilTime"] = value;
            }
        }
    }
}
