//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMIWrappers.Raw {
    
    
    public class Msvm_VirtualSystemSettingData {
        
        private System.Management.ManagementObject _instance;
        
        public Msvm_VirtualSystemSettingData(System.Management.ManagementObject instance) {
            _instance = instance;
        }
        
        protected virtual System.Management.ManagementObject Instance {
            get {
                return _instance;
            }
        }
        
        public virtual string AdditionalRecoveryInformation {
            get {
                return ((string)(_instance["AdditionalRecoveryInformation"]));
            }
            set {
                _instance["AdditionalRecoveryInformation"] = value;
            }
        }
        
        public virtual System.Nullable<bool> AllowFullSCSICommandSet {
            get {
                return ((System.Nullable<bool>)(_instance["AllowFullSCSICommandSet"]));
            }
            set {
                _instance["AllowFullSCSICommandSet"] = value;
            }
        }
        
        public virtual System.Nullable<bool> AllowReducedFcRedundancy {
            get {
                return ((System.Nullable<bool>)(_instance["AllowReducedFcRedundancy"]));
            }
            set {
                _instance["AllowReducedFcRedundancy"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> AutomaticCriticalErrorAction {
            get {
                return ((System.Nullable<ushort>)(_instance["AutomaticCriticalErrorAction"]));
            }
            set {
                _instance["AutomaticCriticalErrorAction"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> AutomaticCriticalErrorActionTimeout {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["AutomaticCriticalErrorActionTimeout"]));
            }
            set {
                _instance["AutomaticCriticalErrorActionTimeout"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> AutomaticRecoveryAction {
            get {
                return ((System.Nullable<ushort>)(_instance["AutomaticRecoveryAction"]));
            }
            set {
                _instance["AutomaticRecoveryAction"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> AutomaticShutdownAction {
            get {
                return ((System.Nullable<ushort>)(_instance["AutomaticShutdownAction"]));
            }
            set {
                _instance["AutomaticShutdownAction"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> AutomaticStartupAction {
            get {
                return ((System.Nullable<ushort>)(_instance["AutomaticStartupAction"]));
            }
            set {
                _instance["AutomaticStartupAction"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> AutomaticStartupActionDelay {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["AutomaticStartupActionDelay"]));
            }
            set {
                _instance["AutomaticStartupActionDelay"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> AutomaticStartupActionSequenceNumber {
            get {
                return ((System.Nullable<ushort>)(_instance["AutomaticStartupActionSequenceNumber"]));
            }
            set {
                _instance["AutomaticStartupActionSequenceNumber"] = value;
            }
        }
        
        public virtual string BaseBoardSerialNumber {
            get {
                return ((string)(_instance["BaseBoardSerialNumber"]));
            }
            set {
                _instance["BaseBoardSerialNumber"] = value;
            }
        }
        
        public virtual string BIOSGUID {
            get {
                return ((string)(_instance["BIOSGUID"]));
            }
            set {
                _instance["BIOSGUID"] = value;
            }
        }
        
        public virtual System.Nullable<bool> BIOSNumLock {
            get {
                return ((System.Nullable<bool>)(_instance["BIOSNumLock"]));
            }
            set {
                _instance["BIOSNumLock"] = value;
            }
        }
        
        public virtual string BIOSSerialNumber {
            get {
                return ((string)(_instance["BIOSSerialNumber"]));
            }
            set {
                _instance["BIOSSerialNumber"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> BootOrder {
            get {
                return ((System.Nullable<ushort>)(_instance["BootOrder"]));
            }
            set {
                _instance["BootOrder"] = value;
            }
        }
        
        public virtual string BootSourceOrder {
            get {
                return ((string)(_instance["BootSourceOrder"]));
            }
            set {
                _instance["BootSourceOrder"] = value;
            }
        }
        
        public virtual string Caption {
            get {
                return ((string)(_instance["Caption"]));
            }
            set {
                _instance["Caption"] = value;
            }
        }
        
        public virtual string ChassisAssetTag {
            get {
                return ((string)(_instance["ChassisAssetTag"]));
            }
            set {
                _instance["ChassisAssetTag"] = value;
            }
        }
        
        public virtual string ChassisSerialNumber {
            get {
                return ((string)(_instance["ChassisSerialNumber"]));
            }
            set {
                _instance["ChassisSerialNumber"] = value;
            }
        }
        
        public virtual string ConfigurationDataRoot {
            get {
                return ((string)(_instance["ConfigurationDataRoot"]));
            }
            set {
                _instance["ConfigurationDataRoot"] = value;
            }
        }
        
        public virtual string ConfigurationFile {
            get {
                return ((string)(_instance["ConfigurationFile"]));
            }
            set {
                _instance["ConfigurationFile"] = value;
            }
        }
        
        public virtual string ConfigurationID {
            get {
                return ((string)(_instance["ConfigurationID"]));
            }
            set {
                _instance["ConfigurationID"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> ConsoleMode {
            get {
                return ((System.Nullable<ushort>)(_instance["ConsoleMode"]));
            }
            set {
                _instance["ConsoleMode"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> CreationTime {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["CreationTime"]));
            }
            set {
                _instance["CreationTime"] = value;
            }
        }
        
        public virtual System.Nullable<uint> DebugChannelId {
            get {
                return ((System.Nullable<uint>)(_instance["DebugChannelId"]));
            }
            set {
                _instance["DebugChannelId"] = value;
            }
        }
        
        public virtual System.Nullable<uint> DebugPort {
            get {
                return ((System.Nullable<uint>)(_instance["DebugPort"]));
            }
            set {
                _instance["DebugPort"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> DebugPortEnabled {
            get {
                return ((System.Nullable<ushort>)(_instance["DebugPortEnabled"]));
            }
            set {
                _instance["DebugPortEnabled"] = value;
            }
        }
        
        public virtual string Description {
            get {
                return ((string)(_instance["Description"]));
            }
            set {
                _instance["Description"] = value;
            }
        }
        
        public virtual string ElementName {
            get {
                return ((string)(_instance["ElementName"]));
            }
            set {
                _instance["ElementName"] = value;
            }
        }
        
        public virtual System.Nullable<bool> GuestControlledCacheTypes {
            get {
                return ((System.Nullable<bool>)(_instance["GuestControlledCacheTypes"]));
            }
            set {
                _instance["GuestControlledCacheTypes"] = value;
            }
        }
        
        public virtual System.Nullable<ulong> HighMmioGapSize {
            get {
                return ((System.Nullable<ulong>)(_instance["HighMmioGapSize"]));
            }
            set {
                _instance["HighMmioGapSize"] = value;
            }
        }
        
        public virtual System.Nullable<bool> IncrementalBackupEnabled {
            get {
                return ((System.Nullable<bool>)(_instance["IncrementalBackupEnabled"]));
            }
            set {
                _instance["IncrementalBackupEnabled"] = value;
            }
        }
        
        public virtual string InstanceID {
            get {
                return ((string)(_instance["InstanceID"]));
            }
            set {
                _instance["InstanceID"] = value;
            }
        }
        
        public virtual System.Nullable<bool> IsSaved {
            get {
                return ((System.Nullable<bool>)(_instance["IsSaved"]));
            }
            set {
                _instance["IsSaved"] = value;
            }
        }
        
        public virtual System.Nullable<bool> LockOnDisconnect {
            get {
                return ((System.Nullable<bool>)(_instance["LockOnDisconnect"]));
            }
            set {
                _instance["LockOnDisconnect"] = value;
            }
        }
        
        public virtual string LogDataRoot {
            get {
                return ((string)(_instance["LogDataRoot"]));
            }
            set {
                _instance["LogDataRoot"] = value;
            }
        }
        
        public virtual System.Nullable<ulong> LowMmioGapSize {
            get {
                return ((System.Nullable<ulong>)(_instance["LowMmioGapSize"]));
            }
            set {
                _instance["LowMmioGapSize"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> NetworkBootPreferredProtocol {
            get {
                return ((System.Nullable<ushort>)(_instance["NetworkBootPreferredProtocol"]));
            }
            set {
                _instance["NetworkBootPreferredProtocol"] = value;
            }
        }
        
        public virtual string Notes {
            get {
                return ((string)(_instance["Notes"]));
            }
            set {
                _instance["Notes"] = value;
            }
        }
        
        public virtual string Parent {
            get {
                return ((string)(_instance["Parent"]));
            }
            set {
                _instance["Parent"] = value;
            }
        }
        
        public virtual System.Nullable<bool> PauseAfterBootFailure {
            get {
                return ((System.Nullable<bool>)(_instance["PauseAfterBootFailure"]));
            }
            set {
                _instance["PauseAfterBootFailure"] = value;
            }
        }
        
        public virtual string RecoveryFile {
            get {
                return ((string)(_instance["RecoveryFile"]));
            }
            set {
                _instance["RecoveryFile"] = value;
            }
        }
        
        public virtual System.Nullable<bool> SecureBootEnabled {
            get {
                return ((System.Nullable<bool>)(_instance["SecureBootEnabled"]));
            }
            set {
                _instance["SecureBootEnabled"] = value;
            }
        }
        
        public virtual string SecureBootTemplateId {
            get {
                return ((string)(_instance["SecureBootTemplateId"]));
            }
            set {
                _instance["SecureBootTemplateId"] = value;
            }
        }
        
        public virtual string SnapshotDataRoot {
            get {
                return ((string)(_instance["SnapshotDataRoot"]));
            }
            set {
                _instance["SnapshotDataRoot"] = value;
            }
        }
        
        public virtual string SuspendDataRoot {
            get {
                return ((string)(_instance["SuspendDataRoot"]));
            }
            set {
                _instance["SuspendDataRoot"] = value;
            }
        }
        
        public virtual string SwapFileDataRoot {
            get {
                return ((string)(_instance["SwapFileDataRoot"]));
            }
            set {
                _instance["SwapFileDataRoot"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> UserSnapshotType {
            get {
                return ((System.Nullable<ushort>)(_instance["UserSnapshotType"]));
            }
            set {
                _instance["UserSnapshotType"] = value;
            }
        }
        
        public virtual string Version {
            get {
                return ((string)(_instance["Version"]));
            }
            set {
                _instance["Version"] = value;
            }
        }
        
        public virtual System.Nullable<bool> VirtualNumaEnabled {
            get {
                return ((System.Nullable<bool>)(_instance["VirtualNumaEnabled"]));
            }
            set {
                _instance["VirtualNumaEnabled"] = value;
            }
        }
        
        public virtual string VirtualSystemIdentifier {
            get {
                return ((string)(_instance["VirtualSystemIdentifier"]));
            }
            set {
                _instance["VirtualSystemIdentifier"] = value;
            }
        }
        
        public virtual string VirtualSystemSubType {
            get {
                return ((string)(_instance["VirtualSystemSubType"]));
            }
            set {
                _instance["VirtualSystemSubType"] = value;
            }
        }
        
        public virtual string VirtualSystemType {
            get {
                return ((string)(_instance["VirtualSystemType"]));
            }
            set {
                _instance["VirtualSystemType"] = value;
            }
        }
    }
}
