//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMIWrappers.Raw {
    
    
    public class Msvm_VirtualSystemManagementService {
        
        private System.Management.ManagementObject _instance;
        
        public Msvm_VirtualSystemManagementService(System.Management.ManagementObject instance) {
            _instance = instance;
        }
        
        protected virtual System.Management.ManagementObject Instance {
            get {
                return _instance;
            }
        }
        
        public virtual System.Nullable<ushort> AvailableRequestedStates {
            get {
                return ((System.Nullable<ushort>)(_instance["AvailableRequestedStates"]));
            }
            set {
                _instance["AvailableRequestedStates"] = value;
            }
        }
        
        public virtual string Caption {
            get {
                return ((string)(_instance["Caption"]));
            }
            set {
                _instance["Caption"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> CommunicationStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["CommunicationStatus"]));
            }
            set {
                _instance["CommunicationStatus"] = value;
            }
        }
        
        public virtual string CreationClassName {
            get {
                return ((string)(_instance["CreationClassName"]));
            }
            set {
                _instance["CreationClassName"] = value;
            }
        }
        
        public virtual string Description {
            get {
                return ((string)(_instance["Description"]));
            }
            set {
                _instance["Description"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> DetailedStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["DetailedStatus"]));
            }
            set {
                _instance["DetailedStatus"] = value;
            }
        }
        
        public virtual string ElementName {
            get {
                return ((string)(_instance["ElementName"]));
            }
            set {
                _instance["ElementName"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> EnabledDefault {
            get {
                return ((System.Nullable<ushort>)(_instance["EnabledDefault"]));
            }
            set {
                _instance["EnabledDefault"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> EnabledState {
            get {
                return ((System.Nullable<ushort>)(_instance["EnabledState"]));
            }
            set {
                _instance["EnabledState"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> HealthState {
            get {
                return ((System.Nullable<ushort>)(_instance["HealthState"]));
            }
            set {
                _instance["HealthState"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> InstallDate {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["InstallDate"]));
            }
            set {
                _instance["InstallDate"] = value;
            }
        }
        
        public virtual string InstanceID {
            get {
                return ((string)(_instance["InstanceID"]));
            }
            set {
                _instance["InstanceID"] = value;
            }
        }
        
        public virtual string Name {
            get {
                return ((string)(_instance["Name"]));
            }
            set {
                _instance["Name"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> OperatingStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["OperatingStatus"]));
            }
            set {
                _instance["OperatingStatus"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> OperationalStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["OperationalStatus"]));
            }
            set {
                _instance["OperationalStatus"] = value;
            }
        }
        
        public virtual string OtherEnabledState {
            get {
                return ((string)(_instance["OtherEnabledState"]));
            }
            set {
                _instance["OtherEnabledState"] = value;
            }
        }
        
        public virtual string PrimaryOwnerContact {
            get {
                return ((string)(_instance["PrimaryOwnerContact"]));
            }
            set {
                _instance["PrimaryOwnerContact"] = value;
            }
        }
        
        public virtual string PrimaryOwnerName {
            get {
                return ((string)(_instance["PrimaryOwnerName"]));
            }
            set {
                _instance["PrimaryOwnerName"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> PrimaryStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["PrimaryStatus"]));
            }
            set {
                _instance["PrimaryStatus"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> RequestedState {
            get {
                return ((System.Nullable<ushort>)(_instance["RequestedState"]));
            }
            set {
                _instance["RequestedState"] = value;
            }
        }
        
        public virtual System.Nullable<bool> Started {
            get {
                return ((System.Nullable<bool>)(_instance["Started"]));
            }
            set {
                _instance["Started"] = value;
            }
        }
        
        public virtual string StartMode {
            get {
                return ((string)(_instance["StartMode"]));
            }
            set {
                _instance["StartMode"] = value;
            }
        }
        
        public virtual string Status {
            get {
                return ((string)(_instance["Status"]));
            }
            set {
                _instance["Status"] = value;
            }
        }
        
        public virtual string StatusDescriptions {
            get {
                return ((string)(_instance["StatusDescriptions"]));
            }
            set {
                _instance["StatusDescriptions"] = value;
            }
        }
        
        public virtual string SystemCreationClassName {
            get {
                return ((string)(_instance["SystemCreationClassName"]));
            }
            set {
                _instance["SystemCreationClassName"] = value;
            }
        }
        
        public virtual string SystemName {
            get {
                return ((string)(_instance["SystemName"]));
            }
            set {
                _instance["SystemName"] = value;
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeOfLastStateChange {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["TimeOfLastStateChange"]));
            }
            set {
                _instance["TimeOfLastStateChange"] = value;
            }
        }
        
        public virtual System.Nullable<ushort> TransitioningToState {
            get {
                return ((System.Nullable<ushort>)(_instance["TransitioningToState"]));
            }
            set {
                _instance["TransitioningToState"] = value;
            }
        }
    }
}
