//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectoverlord.HyperVAdapter {
    
    
    public class Msvm_ComputerSystem {
        
        private System.Management.ManagementObject _instance;
        
        public Msvm_ComputerSystem(System.Management.ManagementObject instance) {
            _instance = instance;
        }
        
        public virtual System.Nullable<ushort> AvailableRequestedStates {
            get {
                return ((System.Nullable<ushort>)(_instance["AvailableRequestedStates"]));
            }
        }
        
        public virtual string Caption {
            get {
                return ((string)(_instance["Caption"]));
            }
        }
        
        public virtual System.Nullable<ushort> CommunicationStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["CommunicationStatus"]));
            }
        }
        
        public virtual string CreationClassName {
            get {
                return ((string)(_instance["CreationClassName"]));
            }
        }
        
        public virtual System.Nullable<ushort> Dedicated {
            get {
                return ((System.Nullable<ushort>)(_instance["Dedicated"]));
            }
        }
        
        public virtual string Description {
            get {
                return ((string)(_instance["Description"]));
            }
        }
        
        public virtual System.Nullable<ushort> DetailedStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["DetailedStatus"]));
            }
        }
        
        public virtual string ElementName {
            get {
                return ((string)(_instance["ElementName"]));
            }
        }
        
        public virtual System.Nullable<ushort> EnabledDefault {
            get {
                return ((System.Nullable<ushort>)(_instance["EnabledDefault"]));
            }
        }
        
        public virtual System.Nullable<ushort> EnabledState {
            get {
                return ((System.Nullable<ushort>)(_instance["EnabledState"]));
            }
        }
        
        public virtual System.Nullable<ushort> EnhancedSessionModeState {
            get {
                return ((System.Nullable<ushort>)(_instance["EnhancedSessionModeState"]));
            }
        }
        
        public virtual System.Nullable<ushort> FailedOverReplicationType {
            get {
                return ((System.Nullable<ushort>)(_instance["FailedOverReplicationType"]));
            }
        }
        
        public virtual System.Nullable<ushort> HealthState {
            get {
                return ((System.Nullable<ushort>)(_instance["HealthState"]));
            }
        }
        
        public virtual string IdentifyingDescriptions {
            get {
                return ((string)(_instance["IdentifyingDescriptions"]));
            }
        }
        
        public virtual System.Nullable<System.DateTime> InstallDate {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["InstallDate"]));
            }
        }
        
        public virtual string InstanceID {
            get {
                return ((string)(_instance["InstanceID"]));
            }
        }
        
        public virtual System.Nullable<System.DateTime> LastApplicationConsistentReplicationTime {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["LastApplicationConsistentReplicationTime"]));
            }
        }
        
        public virtual System.Nullable<System.DateTime> LastReplicationTime {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["LastReplicationTime"]));
            }
        }
        
        public virtual System.Nullable<ushort> LastReplicationType {
            get {
                return ((System.Nullable<ushort>)(_instance["LastReplicationType"]));
            }
        }
        
        public virtual System.Nullable<System.DateTime> LastSuccessfulBackupTime {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["LastSuccessfulBackupTime"]));
            }
        }
        
        public virtual string Name {
            get {
                return ((string)(_instance["Name"]));
            }
        }
        
        public virtual string NameFormat {
            get {
                return ((string)(_instance["NameFormat"]));
            }
        }
        
        public virtual System.Nullable<ushort> NumberOfNumaNodes {
            get {
                return ((System.Nullable<ushort>)(_instance["NumberOfNumaNodes"]));
            }
        }
        
        public virtual System.Nullable<ulong> OnTimeInMilliseconds {
            get {
                return ((System.Nullable<ulong>)(_instance["OnTimeInMilliseconds"]));
            }
        }
        
        public virtual System.Nullable<ushort> OperatingStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["OperatingStatus"]));
            }
        }
        
        public virtual System.Nullable<ushort> OperationalStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["OperationalStatus"]));
            }
        }
        
        public virtual string OtherDedicatedDescriptions {
            get {
                return ((string)(_instance["OtherDedicatedDescriptions"]));
            }
        }
        
        public virtual string OtherEnabledState {
            get {
                return ((string)(_instance["OtherEnabledState"]));
            }
        }
        
        public virtual string OtherIdentifyingInfo {
            get {
                return ((string)(_instance["OtherIdentifyingInfo"]));
            }
        }
        
        public virtual System.Nullable<ushort> PowerManagementCapabilities {
            get {
                return ((System.Nullable<ushort>)(_instance["PowerManagementCapabilities"]));
            }
        }
        
        public virtual string PrimaryOwnerContact {
            get {
                return ((string)(_instance["PrimaryOwnerContact"]));
            }
        }
        
        public virtual string PrimaryOwnerName {
            get {
                return ((string)(_instance["PrimaryOwnerName"]));
            }
        }
        
        public virtual System.Nullable<ushort> PrimaryStatus {
            get {
                return ((System.Nullable<ushort>)(_instance["PrimaryStatus"]));
            }
        }
        
        public virtual System.Nullable<uint> ProcessID {
            get {
                return ((System.Nullable<uint>)(_instance["ProcessID"]));
            }
        }
        
        public virtual System.Nullable<ushort> ReplicationHealth {
            get {
                return ((System.Nullable<ushort>)(_instance["ReplicationHealth"]));
            }
        }
        
        public virtual System.Nullable<ushort> ReplicationMode {
            get {
                return ((System.Nullable<ushort>)(_instance["ReplicationMode"]));
            }
        }
        
        public virtual System.Nullable<ushort> ReplicationState {
            get {
                return ((System.Nullable<ushort>)(_instance["ReplicationState"]));
            }
        }
        
        public virtual System.Nullable<ushort> RequestedState {
            get {
                return ((System.Nullable<ushort>)(_instance["RequestedState"]));
            }
        }
        
        public virtual System.Nullable<ushort> ResetCapability {
            get {
                return ((System.Nullable<ushort>)(_instance["ResetCapability"]));
            }
        }
        
        public virtual string Roles {
            get {
                return ((string)(_instance["Roles"]));
            }
        }
        
        public virtual string Status {
            get {
                return ((string)(_instance["Status"]));
            }
        }
        
        public virtual string StatusDescriptions {
            get {
                return ((string)(_instance["StatusDescriptions"]));
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeOfLastConfigurationChange {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["TimeOfLastConfigurationChange"]));
            }
        }
        
        public virtual System.Nullable<System.DateTime> TimeOfLastStateChange {
            get {
                return ((System.Nullable<System.DateTime>)(_instance["TimeOfLastStateChange"]));
            }
        }
        
        public virtual System.Nullable<ushort> TransitioningToState {
            get {
                return ((System.Nullable<ushort>)(_instance["TransitioningToState"]));
            }
        }
    }
}
