//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectoverlord.HyperVAdapter {
    
    
    public class Msvm_ComputerSystem {
        
        private System.Management.ManagementObject _instance;
        
        public Msvm_ComputerSystem(System.Management.ManagementObject instance) {
            _instance = instance;
        }
        
        public virtual ushort AvailableRequestedStates {
            get {
                return ((ushort)(_instance["AvailableRequestedStates"]));
            }
        }
        
        public virtual string Caption {
            get {
                return ((string)(_instance["Caption"]));
            }
        }
        
        public virtual ushort CommunicationStatus {
            get {
                return ((ushort)(_instance["CommunicationStatus"]));
            }
        }
        
        public virtual string CreationClassName {
            get {
                return ((string)(_instance["CreationClassName"]));
            }
        }
        
        public virtual ushort Dedicated {
            get {
                return ((ushort)(_instance["Dedicated"]));
            }
        }
        
        public virtual string Description {
            get {
                return ((string)(_instance["Description"]));
            }
        }
        
        public virtual ushort DetailedStatus {
            get {
                return ((ushort)(_instance["DetailedStatus"]));
            }
        }
        
        public virtual string ElementName {
            get {
                return ((string)(_instance["ElementName"]));
            }
        }
        
        public virtual ushort EnabledDefault {
            get {
                return ((ushort)(_instance["EnabledDefault"]));
            }
        }
        
        public virtual ushort EnabledState {
            get {
                return ((ushort)(_instance["EnabledState"]));
            }
        }
        
        public virtual ushort EnhancedSessionModeState {
            get {
                return ((ushort)(_instance["EnhancedSessionModeState"]));
            }
        }
        
        public virtual ushort FailedOverReplicationType {
            get {
                return ((ushort)(_instance["FailedOverReplicationType"]));
            }
        }
        
        public virtual ushort HealthState {
            get {
                return ((ushort)(_instance["HealthState"]));
            }
        }
        
        public virtual string IdentifyingDescriptions {
            get {
                return ((string)(_instance["IdentifyingDescriptions"]));
            }
        }
        
        public virtual System.DateTime InstallDate {
            get {
                return ((System.DateTime)(_instance["InstallDate"]));
            }
        }
        
        public virtual string InstanceID {
            get {
                return ((string)(_instance["InstanceID"]));
            }
        }
        
        public virtual System.DateTime LastApplicationConsistentReplicationTime {
            get {
                return ((System.DateTime)(_instance["LastApplicationConsistentReplicationTime"]));
            }
        }
        
        public virtual System.DateTime LastReplicationTime {
            get {
                return ((System.DateTime)(_instance["LastReplicationTime"]));
            }
        }
        
        public virtual ushort LastReplicationType {
            get {
                return ((ushort)(_instance["LastReplicationType"]));
            }
        }
        
        public virtual System.DateTime LastSuccessfulBackupTime {
            get {
                return ((System.DateTime)(_instance["LastSuccessfulBackupTime"]));
            }
        }
        
        public virtual string Name {
            get {
                return ((string)(_instance["Name"]));
            }
        }
        
        public virtual string NameFormat {
            get {
                return ((string)(_instance["NameFormat"]));
            }
        }
        
        public virtual ushort NumberOfNumaNodes {
            get {
                return ((ushort)(_instance["NumberOfNumaNodes"]));
            }
        }
        
        public virtual ulong OnTimeInMilliseconds {
            get {
                return ((ulong)(_instance["OnTimeInMilliseconds"]));
            }
        }
        
        public virtual ushort OperatingStatus {
            get {
                return ((ushort)(_instance["OperatingStatus"]));
            }
        }
        
        public virtual ushort OperationalStatus {
            get {
                return ((ushort)(_instance["OperationalStatus"]));
            }
        }
        
        public virtual string OtherDedicatedDescriptions {
            get {
                return ((string)(_instance["OtherDedicatedDescriptions"]));
            }
        }
        
        public virtual string OtherEnabledState {
            get {
                return ((string)(_instance["OtherEnabledState"]));
            }
        }
        
        public virtual string OtherIdentifyingInfo {
            get {
                return ((string)(_instance["OtherIdentifyingInfo"]));
            }
        }
        
        public virtual ushort PowerManagementCapabilities {
            get {
                return ((ushort)(_instance["PowerManagementCapabilities"]));
            }
        }
        
        public virtual string PrimaryOwnerContact {
            get {
                return ((string)(_instance["PrimaryOwnerContact"]));
            }
        }
        
        public virtual string PrimaryOwnerName {
            get {
                return ((string)(_instance["PrimaryOwnerName"]));
            }
        }
        
        public virtual ushort PrimaryStatus {
            get {
                return ((ushort)(_instance["PrimaryStatus"]));
            }
        }
        
        public virtual uint ProcessID {
            get {
                return ((uint)(_instance["ProcessID"]));
            }
        }
        
        public virtual ushort ReplicationHealth {
            get {
                return ((ushort)(_instance["ReplicationHealth"]));
            }
        }
        
        public virtual ushort ReplicationMode {
            get {
                return ((ushort)(_instance["ReplicationMode"]));
            }
        }
        
        public virtual ushort ReplicationState {
            get {
                return ((ushort)(_instance["ReplicationState"]));
            }
        }
        
        public virtual ushort RequestedState {
            get {
                return ((ushort)(_instance["RequestedState"]));
            }
        }
        
        public virtual ushort ResetCapability {
            get {
                return ((ushort)(_instance["ResetCapability"]));
            }
        }
        
        public virtual string Roles {
            get {
                return ((string)(_instance["Roles"]));
            }
        }
        
        public virtual string Status {
            get {
                return ((string)(_instance["Status"]));
            }
        }
        
        public virtual string StatusDescriptions {
            get {
                return ((string)(_instance["StatusDescriptions"]));
            }
        }
        
        public virtual System.DateTime TimeOfLastConfigurationChange {
            get {
                return ((System.DateTime)(_instance["TimeOfLastConfigurationChange"]));
            }
        }
        
        public virtual System.DateTime TimeOfLastStateChange {
            get {
                return ((System.DateTime)(_instance["TimeOfLastStateChange"]));
            }
        }
        
        public virtual ushort TransitioningToState {
            get {
                return ((ushort)(_instance["TransitioningToState"]));
            }
        }
    }
}
